# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: moddef/v1/document.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'moddef/v1/document.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from moddef.v1 import device_pb2 as moddef_dot_v1_dot_device__pb2
from moddef.v1 import measurand_pb2 as moddef_dot_v1_dot_measurand__pb2
from moddef.v1 import types_pb2 as moddef_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18moddef/v1/document.proto\x12\tmoddef.v1\x1a\x16moddef/v1/device.proto\x1a\x19moddef/v1/measurand.proto\x1a\x15moddef/v1/types.proto\"\x9a\x03\n\x0eModDefDocument\x12\x15\n\x06\x64oc_id\x18\x01 \x01(\tR\x05\x64ocId\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n\x07version\x18\x03 \x01(\tR\x07version\x12+\n\x07imports\x18\x04 \x03(\x0b\x32\x11.moddef.v1.ImportR\x07imports\x12)\n\x05\x65nums\x18\n \x03(\x0b\x32\x13.moddef.v1.EnumTypeR\x05\x65nums\x12/\n\x07structs\x18\x0b \x03(\x0b\x32\x15.moddef.v1.StructTypeR\x07structs\x12>\n\nmeasurands\x18\x0c \x03(\x0b\x32\x1e.moddef.v1.MeasurandDefinitionR\nmeasurands\x12\x46\n\x11measurand_aliases\x18\r \x03(\x0b\x32\x19.moddef.v1.MeasurandAliasR\x10measurandAliases\x12\x32\n\x07\x64\x65vices\x18\x14 \x03(\x0b\x32\x18.moddef.v1.DeviceProfileR\x07\x64\x65vices\"Y\n\x06Import\x12\x10\n\x03uri\x18\x01 \x01(\tR\x03uri\x12\x14\n\x05\x61lias\x18\x02 \x01(\tR\x05\x61lias\x12\'\n\x0f\x63hecksum_sha256\x18\x03 \x01(\tR\x0e\x63hecksumSha256B9Z7github.com/ModDefOrg/moddef/go/genpb/moddef/v1;moddefv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moddef.v1.document_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7github.com/ModDefOrg/moddef/go/genpb/moddef/v1;moddefv1'
  _globals['_MODDEFDOCUMENT']._serialized_start=114
  _globals['_MODDEFDOCUMENT']._serialized_end=524
  _globals['_IMPORT']._serialized_start=526
  _globals['_IMPORT']._serialized_end=615
# @@protoc_insertion_point(module_scope)
