# SPDX-License-Identifier: Apache-2.0

"""Friendly re-exports of the vendored generated protobuf modules.

The wire schema (spec §27) lives in moddef/proto; `moddef/v1/*_pb2.py` are
generated by buf and vendored verbatim (scripts/sync-schema.sh, CI
drift-checked). Import message classes and enums from here rather than the
_pb2 modules.
"""

from __future__ import annotations

from moddef.v1 import device_pb2, document_pb2, mapping_pb2, measurand_pb2, types_pb2

# Document / device model
ModDefDocument = document_pb2.ModDefDocument
Import = document_pb2.Import
DeviceProfile = device_pb2.DeviceProfile
DeviceVariant = device_pb2.DeviceVariant
RegisterBlock = device_pb2.RegisterBlock
Point = device_pb2.Point
Discovery = device_pb2.Discovery
DiscoveryKind = device_pb2.DiscoveryKind
Availability = device_pb2.Availability

# Types
AddressSpace = types_pb2.AddressSpace
AccessMode = types_pb2.AccessMode
ByteOrder = types_pb2.ByteOrder
WordOrder = types_pb2.WordOrder
StorageType = types_pb2.StorageType
PrimitiveType = types_pb2.PrimitiveType
Transport = types_pb2.Transport
Rational = types_pb2.Rational
ValueType = types_pb2.ValueType
EnumType = types_pb2.EnumType
StructType = types_pb2.StructType
FlagSet = types_pb2.FlagSet

# Mapping / transforms / writes
Mapping = mapping_pb2.Mapping
ComposedMapping = mapping_pb2.ComposedMapping
Transform = mapping_pb2.Transform
ScaleRef = mapping_pb2.ScaleRef
ScaleMode = mapping_pb2.ScaleMode
SelectorRef = mapping_pb2.SelectorRef
SelectorCase = mapping_pb2.SelectorCase
NaValue = mapping_pb2.NaValue
BitField = mapping_pb2.BitField
RegisterField = mapping_pb2.RegisterField
StringEncoding = mapping_pb2.StringEncoding
Charset = mapping_pb2.Charset
Padding = mapping_pb2.Padding
Termination = mapping_pb2.Termination
DateTimeSpec = mapping_pb2.DateTimeSpec
DateTimeEncoding = mapping_pb2.DateTimeEncoding
WriteSemantics = mapping_pb2.WriteSemantics
WriteConstraints = mapping_pb2.WriteConstraints
WriteBehavior = mapping_pb2.WriteBehavior

# Measurands
MeasurandDefinition = measurand_pb2.MeasurandDefinition
MeasurandRef = measurand_pb2.MeasurandRef
MeasurandAlias = measurand_pb2.MeasurandAlias
Direction = measurand_pb2.Direction
PhaseRef = measurand_pb2.PhaseRef
Aggregation = measurand_pb2.Aggregation
MeasurementLocation = measurand_pb2.MeasurementLocation
Accumulation = measurand_pb2.Accumulation
